In [1]:
import tensorflow as tf
import numpy as np

**1.** Create a vector, scalar, matrix, and tensor with values of your choosing using ``tf.constant()``

In [5]:
vector = tf.constant([1, 2])
scalar = tf.constant(3)
matrix = tf.constant([[4, 5],
                      [5, 6]])
tensor = tf.constant([[[7, 8, 9],
                       [10, 11, 12],
                       [13, 14, 15]],

                       [[16, 17, 18],
                       [19, 20, 21],
                       [22, 23, 24]]])

**2.** Find the shape, rank and size of the tensors you created in 1.

In [6]:
tensor.shape, tf.rank(tensor), tf.size(tensor)

(TensorShape([2, 3, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=18>)

**3.** Create two tensors containing random values between 0 and 1 with shape ``[5, 300]``.

In [10]:
tensor1 = tf.random.uniform(shape=[5, 300])
tensor2 = tf.random.uniform(shape=[5, 300])
tensor1.shape, tensor2.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

**4.** Multiply the two tensors you created in 3 using matrix multiplication.

In [12]:
tf.matmul(tensor1, tf.transpose(tensor2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[70.56714 , 78.09413 , 72.849976, 74.39967 , 69.00181 ],
       [72.92276 , 82.4951  , 74.57181 , 78.35147 , 73.190704],
       [70.78287 , 80.282   , 71.47493 , 75.38325 , 70.35124 ],
       [73.93631 , 84.1984  , 74.83945 , 80.27523 , 73.36734 ],
       [76.55008 , 88.109314, 79.7055  , 82.79806 , 80.21731 ]],
      dtype=float32)>

**5.** Multiply the two tensors you created in 3 using dot product.

In [15]:
tf.tensordot(tf.transpose(tensor1), tensor2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.57188493, 1.5951959 , 0.62841636, ..., 1.9143573 , 1.8756644 ,
        1.1273524 ],
       [0.4311497 , 1.1224889 , 0.44522542, ..., 1.3573569 , 0.94306225,
        0.8833616 ],
       [0.4560635 , 1.5328941 , 0.4211717 , ..., 1.8017684 , 1.3275837 ,
        0.93470955],
       ...,
       [0.6203675 , 1.1928365 , 0.6234411 , ..., 1.429919  , 0.4738705 ,
        0.9790019 ],
       [0.6833769 , 2.0646267 , 0.8310414 , ..., 2.2922168 , 1.8647269 ,
        1.6766021 ],
       [0.44918287, 0.8925788 , 0.5254667 , ..., 0.9887541 , 0.8597713 ,
        0.5887362 ]], dtype=float32)>

**6.** Create a tensor with random values between 0 and 1 with shape ``[224, 224, 3]``.

In [16]:
tensor3 = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)

**7.** Find the min and max values of the tensor you created in 6 along the first axis.

In [18]:
tf.reduce_min(tensor3, axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[1.57666206e-03, 2.42912769e-03, 2.02775002e-03],
       [5.92648983e-03, 7.89058208e-03, 1.12414360e-03],
       [2.00974941e-03, 1.52373314e-02, 7.82847404e-04],
       [2.70903111e-03, 1.89542770e-04, 6.78670406e-03],
       [4.76539135e-03, 4.82380390e-03, 1.22916698e-03],
       [1.94966793e-03, 9.31954384e-03, 1.13964081e-03],
       [4.59790230e-04, 7.88152218e-03, 4.51946259e-03],
       [2.84159184e-03, 8.30185413e-03, 4.80604172e-03],
       [3.67438793e-03, 2.60162354e-03, 9.62018967e-03],
       [2.23827362e-03, 4.32860851e-03, 6.87086582e-03],
       [1.40500069e-03, 2.38370895e-03, 3.03184986e-03],
       [3.08811665e-03, 3.69310379e-04, 1.99794769e-03],
       [3.80241871e-03, 7.42423534e-03, 1.35672092e-02],
       [7.33518600e-03, 5.94031811e-03, 2.80141830e-04],
       [1.00541115e-03, 1.33180618e-03, 1.68931484e-03],
       [7.93445110e-03, 2.13134289e-03, 5.94878197e-03],
       [9.52100754e-03, 2.36749649e-04

**8.** Create a tensor with random values of shape ``[1, 224, 224, 3]`` then squeeze it to change the shape to ``[224, 224, 3]``.

In [20]:
tensor4 = tf.random.uniform(shape=[1, 224, 224, 3])
tensor4_squeezed = tf.squeeze(tensor4)
tensor4.shape, tensor4_squeezed.shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

**9.** Create a tensor with shape ``[10]`` using your own choice of values, the find the index which has the maximum value.

In [21]:
tensor5 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tf.argmax(tensor5)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

**10.** One-hot encode the tensor you created in 9.

In [25]:
tf.one_hot(tensor5, depth=11)

<tf.Tensor: shape=(10, 11), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>